#!/bin/bash

SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${SCRIPT_PATH}/riptide-ros" || exit

for package in riptide_*
do
    rosdoc_lite "${package}" -o "${SCRIPT_PATH}/doxygen/api/${package}"
done

cd "${SCRIPT_PATH}/ghp-import" || exit

echo $(dirname $SCRIPT_PATH)
